api/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
import datetime,random
from decouple import config
from .views import RootAPI
from blog import apiView as blog_api

app_name = "api"
urlpatterns = [

    path("",RootAPI.as_view(),name="home"),
    
    # BLOG
    path("blog/",blog_api.BlogPostView.as_view(),name="blog"),
    path("blog/<str:pk>/",blog_api.BlogIndividualPostView.as_view(),name="blog_instance"),

]

blog/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
import datetime,random
from decouple import config
from .views import latest_post,specificPost

app_name = "blog"
urlpatterns = [
    path('',latest_post,name="home"),
    path('blog/<page>',latest_post,name="latest_p"),
    path('post/<str:postId>',specificPost,name="specific_post"),


]

neosol/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.views.static import serve
from django.conf import settings
import datetime,random
from decouple import config
from .views import home

urlpatterns = [

    # path(f'admin-{eval(config("ADMIN_ROUTE",default="True"))}/', admin.site.urls,name="admin"),
    path('', home,name="home"),
    path('admin/', admin.site.urls),
    # LOCAL APPS ROUTES
    path('api/',include('api.urls'),name="api"),
    path('blog/',include('blog.urls'),name="blog"),
    path('toolkit/',include('toolkit.urls'),name="toolkit"),

    # URLS TO SERVE STATIC and MEDIA Files
    # re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATIC_ROOT}),
    re_path(r'^static/(?P<path>.*)$', serve,{'document_root': settings.STATICFILES_DIRS[0]}),
    re_path(r'^media/(?P<path>.*)$', serve,{'document_root': settings.MEDIA_ROOT}),
]

toolkit/urls.py
from django.contrib import admin
from django.urls import path,include,re_path
from django.conf import settings
import datetime,random
from decouple import config

urlpatterns = [



]

api/models.py
from django.db import models

# Create your models here.

blog/models.py
# INTERNAL APPS
from django.db import models

# LOCAL APPS
from toolkit.mongotools import Mongodb

# Create your models here.
def auto_id():
    collection = Mongodb("blog")
    return str(collection.filter({}).count()+1)

class BlogPost(models.Model):
    postId = models.CharField(max_length=10,default=auto_id,unique=True)
    title = models.CharField(max_length=100)
    subTitle = models.CharField(max_length=100)
    image = models.ImageField()
    publishDate = models.DateTimeField()
    draft = models.BooleanField()
    tag = models.JSONField()
    content = models.TextField()

    json_field = ["tag"]

    # Clean_<field_name> works on admin default db model
    def clean_tag(self):
        print(type(self.tag))
        
        return self.tag.split(",")

toolkit/models.py
from django.db import models

# Create your models here.
class Mongo_Credentials(models.Model):
    use = models.CharField(max_length=100)
    db = models.CharField(max_length=100)
    collection = models.CharField(max_length=100)
    uri = models.CharField(max_length=100)
    status = models.BooleanField(default=False)

    def __str__(self):
        return self.use

# class Bucket_Credentials(models.Model):
#     use = models.CharField(max_length=100)
#     bucket = models.CharField(max_length=100)
#     location = models.CharField(max_length=100)
#     access_key = models.CharField(max_length=100)
#     access_secret = models.BooleanField(default=False)

#     def __str__(self):
#         return self.use

blog/forms.py
from django import forms
from .models import BlogPost
# Import From THIRDPARTY Package
from markdownx.models import MarkdownxFormField

class BlogForm(forms.ModelForm):
    content = MarkdownxFormField()
    class Meta:
        model = BlogPost
        fields= "__all__"
    

api/views.py
# INTERNAL MODULES
from django.shortcuts import render

# EXTERNAL MODULES
from rest_framework.views import APIView,Response
from rest_framework.reverse import reverse

# LOCAL MODULES


# Create your views here.
class RootAPI(APIView):
    def get(self, request):
        data = {
            'Blog': reverse('api:blog', request=request),
        }
        return Response(data)

blog/views.py
# INTERNAL
from django.shortcuts import render

# LOCAL
from toolkit.mongotools import Mongodb

# EXTERNAL

# Create your views here.
def latest_post(request,page=0):
    c_page = int(page)
    Blog = Mongodb("blog")
    limit = 9
    query = {}
    count = Blog.filter(query=query).count()
    pages = -(-count//limit)
    skips = {i:i*limit for i in range(pages) if i*limit < count}
    output = [i for i in Blog.filter({},limit=limit,projection={"content":0},skip=c_page*limit)]
    context = {"output":output,"pages":skips,"current_p": c_page,"limit":limit}
    return render(request,'blog/latest_post.html',context=context)

def specificPost(request,postId=1):
    c_page = 0
    Blog = Mongodb("blog")
    limit = 10
    query = {}
    count = Blog.filter(query=query).count()
    pages = count//limit
    skips = {i:i*limit for i in range(pages) if i*limit < count}
    query = {"postId":postId}
    output = [i for i in Blog.filter(query,projection={"postId":0,"_id":0})]
    context = {"post":output[0],"pages":skips,"current_p": c_page}
    return render(request,'blog/specific_post.html',context=context)


    

neosol/views.py
from django.shortcuts import render

def home(request):
    context = {

    }
    
    return render(request,'home.html',context=context)

toolkit/views.py
from django.shortcuts import render

# Create your views here.

blog/templates/blog/latest_post.html
{% extends 'base_template.html' %}
{% load static %}
{% load template_extra %}

{% block head %}
<style>
    .card_img {
        background-blend-mode:lighten;
        background-repeat: no-repeat;
        background-position: center center;
        background-size: 1%;
    }
</style>
{% endblock head %}

{% block preload %}{% endblock preload %}

{% block header %}
<div class="row mb-2">
    <div class="col-sm-4">
        <h1 class="m-0">BLOG</h1>
    </div><!-- /.col -->
    <div class="col-sm-4">
        {% for i,j in pages.items %}
        {% if i < current_p|add:5 or i > current_p|add:-5  %}
        <a href="{% url 'blog:latest_p' i %}">
            <span class="btn btn-{% if i == current_p %}info{% else %}secondary{% endif %}">{{ i|add:1 }}</span>
        </a>
        {% endif %}
        {% endfor %}
    </div>
    <div class="col-sm-4">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Blog</a></li>
            <li class="breadcrumb-item active">Dashboard v1</li>
            <li class="breadcrumb-item active">Dashboard v1</li>
        </ol>
    </div><!-- /.col -->
</div><!-- /.row -->
{% endblock header %}

{% block maincontent %}
<div class="card-columns">
    {% for post in output %}

    <div class="card">
        {% comment %} <img class="card_img card-img-top " src="{{ post.image }}" alt="Card image cap"> {% endcomment %}
        <div class="card_image py-5" style="background-image:url({{ post.image }});">
            <div class="text-center">
                {% for i in post.tag %}<div class="btn-sm m-1 btn-dark d-inline-block">{{ i }}</div>{% endfor %}
            </div>
        </div>
        <div class="card-body">
            <h5 class="card-title">{{ post.title }}</h5>
            <p class="card-text">{{ post.subTitle }}</p>
        </div>
        <div class="card-footer">
            <small class="text-muted">{{ post.publishDate }}</small>
            <a href="{% url 'blog:specific_post' post.postId %}"><span class="btn-sm btn-info">View</span></a>
            <a href="{% url 'api:blog_instance' post.postId %}"><span class="btn-sm btn-warning">Edit</span></a>
        </div>
    </div>
    {% endfor %}
</div>


{% endblock maincontent %}

blog/templates/blog/specific_post.html
{% extends 'base_template.html' %}
{% load template_extra %}
{% load static %}

{% block head %}
<link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
{% endblock head %}

{% block preload %}{% endblock preload %}

{% block header %}
<div class="row mb-2">
  <div class="col-sm-4">
    <h1 class="m-0">BLOG</h1>
  </div><!-- /.col -->
  <div class="col-sm-4">

  </div>
  <div class="col-sm-4">
    <ol class="breadcrumb float-sm-right">
      <li class="breadcrumb-item"><a href="{% url 'blog:home' %}">Blog</a></li>
      <li class="breadcrumb-item active">Dashboard v1</li>
      <li class="breadcrumb-item active">Dashboard v1</li>
    </ol>
  </div><!-- /.col -->
</div><!-- /.row -->
{% endblock header %}


{% block maincontent %}

<div class="card mb-auto">
  <div class="card_image py-5" style="background-image:linear-gradient(to right,rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0.0)),url({{ post.image }});">
    <div class="card-body" style="color:white">
      <h5 class="card-title">{{ post.title }}</h5>
      <p class="card-text">Aman{{ post.subTitle }}</p>
      <p class="card-text">{% for i in post.tag %}<span class="btn-sm m-1 btn-success">{{ i }}</span>{% endfor %}</p>
      <p class="card-text"><small class="text-muted">{{ post.publishDate }}</small></p>
    </div>
  </div>
  <div class="card-body">
    <p class="card-text"><small class="text-muted">{{ post.content|markdown }}</small></p>
  </div>
</div>

{% endblock maincontent %}

templates/home.html
{% extends 'base_template.html' %}

toolkit/templates/base_template.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    {% include 'components/head.html' %}
    {% block head %}{% endblock head %}
</head>

<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">

        <!-- Preloader -->
        {% block preload %}
        <div class="preloader flex-column justify-content-center align-items-center">
            <img class="animation__shake" src="{% static 'dist/img/NeoLogo.png' %}" alt="AdminLTELogo" height="60" width="60">
        </div>
        {% endblock preload %}

        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            {% block navbar %}
            {% include 'components/navbar.html' %}
            {% endblock navbar %}
        </nav>

        <!-- Main Sidebar Container -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            {% block brandlogo %}
            <a href="/admin" class="brand-link">
                <img src="{% static 'dist/img/NeoLogo.png' %}" alt="AdminLTE Logo" class="brand-image img-circle elevation-3"
                    style="opacity: .8">
                <span class="brand-text font-weight-light">Aman Solutions</span>
            </a>
            {% endblock brandlogo %}

            <!-- Sidebar -->
            <div class="sidebar">
                {% block leftbar %}
                {% include 'components/leftbar.html' %}
                {% endblock leftbar %}
            </div>
            <!--/ Left Sidebar-->
        </aside>
        <!--/ Aside-->

        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <div class="content-header">
                <div class="container-fluid">
                    {% block header %}
                    {% include 'components/header.html' %}
                    {% endblock header %}
                </div>
            </div>
            <!-- / Content Header (Page header) -->

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    {% block maincontent %}

                    {% endblock maincontent %}
                </div>
            </section>
            <!-- / Main content -->

        </div>
        <!-- / Content Wrapper. Contains page content -->

        <!-- Footer -->
        <footer class="main-footer">
            {% block footer %}
                {% include 'components/footer.html' %}            
            {% endblock footer %}
        </footer>
        <!-- / Footer -->

        <!-- Control Sidebar -->
        <aside class="control-sidebar control-sidebar-dark">
            {% block rightbar %}
            
            {% endblock rightbar %}
        </aside>
        <!-- /.control-sidebar -->








    </div>
    <!--Wrapper-->

    {% include 'components/scripts.html' %}
    {% block script %}{% endblock script %}

</body>

<script>

</script>

toolkit/templates/components/footer.html
<strong>Copyright &copy; 2014-2021 <a href="https://adminlte.io">AdminLTE.io</a>.</strong>
All rights reserved.
<div class="float-right d-none d-sm-inline-block">
    <b>Version</b> 3.1.0
</div>

toolkit/templates/components/head.html
{% load static %}
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{% block title %}Aman | Solution{% endblock title %}</title>
<link rel="icon" href="{% static 'dist/img/NeoLogo.png' %}" type="image/png" sizes="32x32">
<!-- Google Font: Source Sans Pro -->
<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
<!-- Font Awesome -->
<link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">
<!-- Ionicons -->
<link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
<!-- Tempusdominus Bootstrap 4 -->
<link rel="stylesheet" href="{% static 'plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css' %}">
<!-- iCheck -->
<link rel="stylesheet" href="{% static 'plugins/icheck-bootstrap/icheck-bootstrap.min.css' %}">
<!-- JQVMap -->
<link rel="stylesheet" href="{% static 'plugins/jqvmap/jqvmap.min.css' %}">
<!-- Theme style -->
<link rel="stylesheet" href="{% static 'dist/css/adminlte.min.css' %}">
<!-- overlayScrollbars -->
<link rel="stylesheet" href="{% static 'plugins/overlayScrollbars/css/OverlayScrollbars.min.css' %}">
<!-- Daterange picker -->
<link rel="stylesheet" href="{% static 'plugins/daterangepicker/daterangepicker.css' %}">
<!-- summernote -->
<link rel="stylesheet" href="{% static 'plugins/summernote/summernote-bs4.min.css' %}">
<!--Pygments-->
<link rel="stylesheet" href="{% static 'dist/css/pygmnt.css' %}">

toolkit/templates/components/header.html
<div class="row mb-2">
    <div class="col-sm-6">
        <h1 class="m-0">Dashboard</h1>
    </div><!-- /.col -->
    <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Dashboard v1</li>
        </ol>
    </div><!-- /.col -->
</div><!-- /.row -->

toolkit/templates/components/leftbar.html
     {% load static %}
      <!-- Sidebar user panel (optional) -->
      <div class="user-panel mt-3 pb-3 mb-3 d-flex">
      {% block leftbaruser %}
          <div class="image">
              <img src="{% static 'dist/img/adminLogo.jpg' %}" class="img-circle elevation-2" alt="User Image">
          </div>
          <div class="info">
              <a href="/admin" class="d-block">Aman Patel</a>
          </div>
      {% endblock leftbaruser %}
      </div>

      <!-- SidebarSearch Form -->
      <div class="form-inline">
          {% block leftbarsearch %}
          <div class="input-group" data-widget="sidebar-search">
              <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
              <div class="input-group-append">
                  <button class="btn btn-sidebar">
                      <i class="fas fa-search fa-fw"></i>
                  </button>
              </div>
          </div>
          {% endblock leftbarsearch %}
      </div>

      <!-- Sidebar Menu -->
      <nav class="mt-2">
          {% block leftbarmenu %}
          <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="true">
              <!-- Add icons to the links using the .nav-icon class
               with font-awesome or any other icon font library -->
              <li class="nav-item menu-open">
                  <a href="#" class="nav-link active">
                      <i class="nav-icon fas fa-tachometer-alt"></i>
                      <p>
                          Blog
                          <i class="right fas fa-angle-left"></i>
                      </p>
                  </a>
                  <ul class="nav nav-treeview">
                      <li class="nav-item">
                          <a href="{% url 'blog:latest_p' 0 %}" class="nav-link active">
                              <i class="far fa-circle nav-icon"></i>
                              <p>Latest</p>
                          </a>
                      </li>
                      <li class="nav-item">
                          <a href="{% url 'blog:latest_p' 0 %}" class="nav-link">
                              <i class="far fa-circle nav-icon"></i>
                              <p>Trending</p>
                          </a>
                      </li>
                      <li class="nav-item">
                          <a href="{% url 'blog:latest_p' 0 %}" class="nav-link">
                              <i class="far fa-circle nav-icon"></i>
                              <p>Last Year</p>
                          </a>
                      </li>
                  </ul>
              </li>
              {% comment %} <li class="nav-header">LABELS</li>
              <li class="nav-item">
                  <a href="#" class="nav-link">
                      <i class="nav-icon far fa-circle text-danger"></i>
                      <p class="text">Important</p>
                  </a>
              </li>
              <li class="nav-item">
                  <a href="#" class="nav-link">
                      <i class="nav-icon far fa-circle text-warning"></i>
                      <p>Warning</p>
                  </a>
              </li>
              <li class="nav-item">
                  <a href="#" class="nav-link">
                      <i class="nav-icon far fa-circle text-info"></i>
                      <p>Informational</p>
                  </a>
              </li> {% endcomment %}
          </ul>
          {% block addleftbar %}
          {% endblock addleftbar %}
          {% endblock leftbarmenu %}
      </nav>
      <!-- /.sidebar-menu -->

toolkit/templates/components/navbar.html
<!-- Left navbar links -->
<ul class="navbar-nav">
    {% block leftnavbar %}
    <li class="nav-item">
        <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'home' %}" class="nav-link">Home</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'blog:home' %}" class="nav-link">Blog</a>
    </li>
    <li class="nav-item d-none d-sm-inline-block">
        <a href="{% url 'api:home' %}" class="nav-link">API</a>
    </li>
    {% block addleftnavbar %}
    {% endblock addleftnavbar %}

    {% endblock leftnavbar %}
</ul>

<!-- Right navbar links -->
<ul class="navbar-nav ml-auto">
    {% block rightnavbar %}
    <!-- Navbar Search -->
    <li class="nav-item">
        <a class="nav-link" data-widget="navbar-search" href="#" role="button">
            <i class="fas fa-search"></i>
        </a>
        <div class="navbar-search-block">
            <form class="form-inline">
                <div class="input-group input-group-sm">
                    <input class="form-control form-control-navbar" type="search" placeholder="Search"
                        aria-label="Search">
                    <div class="input-group-append">
                        <button class="btn btn-navbar" type="submit">
                            <i class="fas fa-search"></i>
                        </button>
                        <button class="btn btn-navbar" type="button" data-widget="navbar-search">
                            <i class="fas fa-times"></i>
                        </button>
                    </div>
                </div>
            </form>
        </div>
    </li>
    {% block addrightnavbar %}
    {% endblock addrightnavbar %}

    {% endblock rightnavbar %}
</ul>

toolkit/templates/components/scripts.html
{% load static %}
<!-- jQuery -->
<script src="{% static 'plugins/jquery/jquery.min.js' %}"></script>
<!-- jQuery UI 1.11.4 -->
<script src="{% static 'plugins/jquery-ui/jquery-ui.min.js' %}"></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button)
</script>
<!-- Bootstrap 4 -->
<script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
<!-- ChartJS -->
<script src="{% static 'plugins/chart.js/Chart.min.js' %}"></script>
<!-- Sparkline -->
<script src="{% static 'plugins/sparklines/sparkline.js' %}"></script>
<!-- JQVMap -->
<script src="{% static 'plugins/jqvmap/jquery.vmap.min.js' %}"></script>
<script src="{% static 'plugins/jqvmap/maps/jquery.vmap.usa.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'plugins/jquery-knob/jquery.knob.min.js' %}"></script>
<!-- daterangepicker -->
<script src="{% static 'plugins/moment/moment.min.js' %}"></script>
<script src="{% static 'plugins/daterangepicker/daterangepicker.js' %}"></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src="{% static 'plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js' %}"></script>
<!-- Summernote -->
<script src="{% static 'plugins/summernote/summernote-bs4.min.js' %}"></script>
<!-- overlayScrollbars -->
<script src="{% static 'plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dist/js/adminlte.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dist/js/demo.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'dist/js/pages/dashboard.js' %}"></script>